import { Voxel } from '../types';
import { MaterialId, faceColor, paper, gridline } from '../core/palette';
import { projectModel, IsoVoxel } from '../core/iso';
import { facesToSVG } from '../core/svg';

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateSVGTurnaround(
  voxels: Voxel[],
  width = 1600,
  height = 500,
  showDividers = true
): string {
  const isoVoxels: IsoVoxel[] = voxels.map((v) => ({
    x: v.x,
    y: v.y,
    z: v.z,
    material: (v.type || (v as any).material || 'rock') as MaterialId,
  }));

  const faces = projectModel(isoVoxels, width, height);
  let svg = facesToSVG(faces, width, height, paper);

  if (showDividers) {
    const cellWidth = width / 4;
    let dividerLines = '';
    for (let i = 1; i < 4; i++) {
      const x = i * cellWidth;
      dividerLines += `<line x1="${x}" y1="0" x2="${x}" y2="${height}" stroke="${gridline}" stroke-width="1"/>`;
    }
    svg = svg.replace('</svg>', `${dividerLines}</svg>`);
  }

  return svg;
}

export function generateOBJModel(voxels: Voxel[]): string {
  let obj = `# Stone Wolf Voxel Model (.OBJ)\n`;
  obj += `# Generated by Stone Wolf Turnaround Studio\n\n`;

  const materialsUsed = new Set<MaterialId>();
  for (const v of voxels) {
    const mat = (v.type || (v as any).material || 'rock') as MaterialId;
    materialsUsed.add(mat);
  }

  for (const mat of materialsUsed) {
    const topCol = faceColor(mat, 'top');
    const frontCol = faceColor(mat, 'front');
    const sideCol = faceColor(mat, 'side');
    obj += `# Material '${mat}': top=${topCol}, front=${frontCol}, side=${sideCol}\n`;
  }
  obj += `\n`;

  let vertIndex = 1;

  for (const v of voxels) {
    const x = v.x;
    const y = v.y;
    const z = v.z;

    obj += `v ${x} ${y} ${z}\n`;
    obj += `v ${x + 1} ${y} ${z}\n`;
    obj += `v ${x + 1} ${y + 1} ${z}\n`;
    obj += `v ${x} ${y + 1} ${z}\n`;
    obj += `v ${x} ${y} ${z + 1}\n`;
    obj += `v ${x + 1} ${y} ${z + 1}\n`;
    obj += `v ${x + 1} ${y + 1} ${z + 1}\n`;
    obj += `v ${x} ${y + 1} ${z + 1}\n`;

    const i = vertIndex;
    obj += `f ${i} ${i + 1} ${i + 2} ${i + 3}\n`;
    obj += `f ${i + 5} ${i + 4} ${i + 7} ${i + 6}\n`;
    obj += `f ${i + 4} ${i} ${i + 3} ${i + 7}\n`;
    obj += `f ${i + 1} ${i + 5} ${i + 6} ${i + 2}\n`;
    obj += `f ${i + 4} ${i + 5} ${i + 1} ${i}\n`;
    obj += `f ${i + 3} ${i + 2} ${i + 6} ${i + 7}\n`;

    vertIndex += 8;
  }

  return obj;
}
